services:
  postgres:
    image: 'postgres:14.6-alpine'
    environment:
      - 'POSTGRES_DB=smart_home'
      - 'POSTGRES_PASSWORD=pswd'
      - 'POSTGRES_USER=admin'
    ports:
      - '5432:5432'
